;; ********************************
;; *** Author: PZH Gesellschaft ***
;; *** Date: 11. Mai. 2026      ***
;; *** Update: 11. Mai. 2026    ***
;; *** License: AGPL-3-or-later ***
;; ********************************

%ifndef BOOTLOADER_GLOBAL_INC
%define BOOTLOADER_GLOBAL_INC

;; **************
;; *** Macros ***
;; **************

;; ***************
;; *** Aliases ***
;; ***************

;; ******************
;; *** Structures ***
;; ******************

;; ************************
;; *** Global Variables ***
;; ************************

extern image_handle
extern system_table

extern ConOut
extern OutputString

%endif