;; ********************************
;; *** Author: PZH Gesellschaft ***
;; *** Date: 11. Mai. 2026      ***
;; *** Update: 11. Mai. 2026    ***
;; *** License: AGPL-3-or-later ***
;; ********************************

%ifndef BOOTLOADER_STDIO_INC
%define BOOTLOADER_STDIO_INC

;; **************
;; *** Macros ***
;; **************

;; ***************
;; *** Aliases ***
;; ***************

;; ******************
;; *** Structures ***
;; ******************

;; *****************
;; *** Functions ***
;; *****************

extern puts

%endif